//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class licensii4
    {
        public int id_table { get; set; }
        public string kategoria { get; set; }
        public string kol_sklad { get; set; }
        public string url_kartinki { get; set; }
        public Nullable<int> zena { get; set; }
    }
}
