//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazi
    {
        public int id_zakaza { get; set; }
        public string user { get; set; }
        public string konfiguracia { get; set; }
        public Nullable<int> zena { get; set; }
        public string Image { get; set; }
    }
}
